# Site settings
title: Raison Zone
email: raisonwen@gmail.com
url: raisonwen.github.io
description: "Wellcome to contact me."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: http://raisonwen.github.io/

# Footer settings
footer: Raison Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
  - title: facebook
    url: https://www.facebook.com/raison.wen
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/RaisonWen/raisonwen.github.io
  - title: google-plus
    url: https://plus.google.com/114807637782392437720

# Build settings
markdown: kramdown
permalink: pretty
