
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://panossakkos.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /raisonwen.github.io

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Raison Wen"
title: "{ Raison Wen }"
description: "Blog and website of Raison Wen."
keywords: "smith, raison, personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 100
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "做人如果没梦想"
  - text: "跟咸鱼有什么分别?"

me-img: "/img/head-v.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/codercat.png"
    date: "December 2013 - Today"
    description: "Working at Tuniu"
  - image: "/img/timeline/total-eclipse-of-the-octocat.png"
    date: "February 2012 - November 2013"
    description: "Worked at Suning as a Coder"
  - image: "/img/timeline/hipster-partycat.png"
    date: "September 2008 - June 2012"
    description: "Studied computer science and technology at Anhui Normal University. Intrested in student union activity and film"
  - image: "/img/timeline/dodgetocat.png"
    date: "September 2005 - June 2008"
    description: "Studied at ChuZhou Senior Middle School. Intrested in science and film"
  - image: "/img/timeline/jetpacktocat.png"
    date: "September 2002 - June 2005"
    description: "Studied at ChuZhou NO.2 Junior High School. Intrested in painting, cartoon, physics and mathematics."
  - image: "/img/timeline/welcometocat.png"
    date: "September 1996 - June 2002"
    description: "Studied at ChuZhou NO.1 Primary School. Intrested in painting, ping-pong, basketball and so on."
  - image: "/img/timeline/inflatocat.png"
    date: "22nd July 1990"
    description: "Borned"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "raisonwen@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "我是一个闲散的人. 程序猿. 但我确有个性, 很易相处. 偶尔虽然会脾气不好, 但向来对事不对人, 放心, 7秒之后我就会忘了它, 别放在心上."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/raison.wen"
  - title: "github"
    url: "https://github.com/RaisonWen/raisonwen.github.io"


############
# 404 page #
############

404img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
